[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "4.1.7"
fibonacci-lib = { path = "../lib" }
core = { path = "../../pdf-utils/core" }


