name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [main, dev]
    paths:
      - "docs/**"
      - ".github/workflows/deploy-docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages-docs"
  cancel-in-progress: false

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages-docs
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install mdbook
        run: cargo install mdbook

      - name: Build documentation
        run: |
          cd docs
          chmod +x build.sh
          ./build.sh

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book

      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
