[package]
name = "wasm"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib"]

[dependencies]
core = {path = "../core"}
extractor = {path ="../extractor"}
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }